### ISSUE TITLE
AttributeError: module 'pyparsing' has no attribute 'operatorPrecedence'

### ISSUE THREAD

**Issue by r-ithikinwisconsin** [RUB-SysSec/gadget_synthesis#3]
This has been depracted. You can fix it by replacing:
gadget_synthesis/lib/miasm/miasm/core/cpu.py", line 395: `base_expr = pyparsing.operatorPrecedence(operand, ` with `base_expr = pyparsing.infixNotation(operand,` 

:)

**Comment by mu00d8** [comment]
Thanks for reporting and working out a fix! 

The issue is upstream in Miasm, which hasn't migrated yet to pyparsing 3.x. For now, they pin pyparsing to version 2.0 (cf. https://github.com/cea-sec/miasm/commit/c6ed2932f8892274187c99cad6ef27e29d142dd6). To maintain compatibility, I'll pin Miasm's dependencies to the versions used for the paper.
