### ISSUE TITLE
How to create the payload with no stack offset ?

### ISSUE THREAD

**Issue by ZoEplA** [RUB-SysSec/gadget_synthesis#4]
Hi, I read the SGC paper and tried to use it, automating ROP with SMT is a really good idea!!! But I have a question in the process of using SGC:

I found that when SGC constructs "ptr_postconditions", it will store data on the stack and use the stack address as a pointer, but if we can't leak the stack address, How to use SGC to construct the exploit? Why not symbolize the memory area? Am I overlooking some features of SGC? Looking forward to your reply!

**Comment by mu00d8** [comment]
Hi,

thanks for your interest in SGC!
 
The "ptr_postconditions" are used when you want your register to contain an address of something, but you don't really care about the address itself, only the value it is pointing to. The SMT solver will then choose a suitable address automatically, at which it can place the value you care about. 
In your case, you see the chosen addresses being on the stack because most likely, your target configuration declares the stack as writable. You can control this behavior by setting "write_mem_areas" in the target configuration. Remember that each writable area is also automatically readable and make sure "restrict_mem" in synthesizer_config_default.json is set to true.

Does that help?

**Comment by ZoEplA** [comment]
Thank you, I have understood, thank you for your answer!
